# 📈 Stock Portfolio Optimization & Risk Analysis

## Notebook 01: Data Collection

### Objective
Download historical stock price data using Yahoo Finance, inspect the data quality, and save the raw dataset for further analysis.

### Stocks Analyzed
- Reliance Industries
- Infosys
- TCS
- SBI
- LT
- Bharti Airtel
- (and other selected stocks)

### Tools Used
- Python
- Pandas
- NumPy
- yfinance
- Matplotlib
- Jupyter Notebook

In [31]:
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt

# Display settings
pd.set_option("display.max_columns", None)
plt.style.use("ggplot")

In [32]:
# Section 2 – Define Stock Tickers (NSE)

tickers = [
    "RELIANCE.NS",      # Reliance Industries
    "TCS.NS",           # Tata Consultancy Services
    "HDFCBANK.NS",      # HDFC Bank
    "ICICIBANK.NS",     # ICICI Bank
    "INFY.NS",          # Infosys
    "SBIN.NS",          # State Bank of India
    "LT.NS",            # Larsen & Toubro
    "BHARTIARTL.NS",    # Bharti Airtel
    "ITC.NS",           # ITC
    "HINDUNILVR.NS"     # Hindustan Unilever
]

In [33]:


data = yf.download(
    tickers,
    start="2021-01-01",
    end=datetime.today().strftime("%Y-%m-%d"),
    auto_adjust=False,
    group_by="ticker"
)

[*********************100%***********************]  10 of 10 completed

In [34]:
data.head()

Ticker     RELIANCE.NS                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2021-01-01  917.461670  921.615173  914.692688  917.230957  897.047058
2021-01-04  920.738342  922.492004  908.231689  918.776978  898.559082
2021-01-05  908.693176  915.431091  902.693665  907.354858  887.388306
2021-01-06  907.262512  907.308655  879.226440  883.426086  863.986145
2021-01-07  886.310425  897.617188  879.226440  881.995422  862.586975

Ticker               ICICIBANK.NS                                      \
Price         Volume         Open        High         Low       Close
Date
2021-01-01  10015175   535.549988  537.000000  526.099976  527.500000
2021-01-04  24513534   532.299988  535.000000  524.299988  531.700012
2021-01-05  24123091   526.650024  539.950012  523.000000  537.250000
2021-01-06  46401468   538.750000  550.599976  535.849976  546.700012
2021-01-07  32325918   552.150024  554.400024  539.750000  541.099976

Ticker                                 TCS.NS                            \
Price        Adj Close    Volume         Open         High          Low
Date
2021-01-01  505.926270  13592625  2880.000000  2940.000000  2879.000000
2021-01-04  509.954498  16549750  2950.000000  3050.750000  2940.949951
2021-01-05  515.277527  23311516  3039.600098  3114.250000  3039.600098
2021-01-06  524.340942  28178838  3100.000000  3113.500000  3037.199951
2021-01-07  518.969971  21138034  3075.000000  3080.850098  3000.250000

Ticker                                            SBIN.NS              \
Price             Close    Adj Close   Volume        Open        High
Date
2021-01-01  2928.250000  2521.074219  2681440  274.899994  280.000000
2021-01-04  3039.449951  2616.812012  5113293  281.850006  283.899994
2021-01-05  3093.000000  2662.915527  5801309  278.049988  282.450012
2021-01-06  3051.500000  2627.186768  3726716  283.000000  289.149994
2021-01-07  3032.800049  2611.086182  3717827  289.000000  291.799988

Ticker                                                        INFY.NS  \
Price              Low       Close   Adj Close    Volume         Open
Date
2021-01-01  274.399994  279.399994  253.242310  24531791  1257.900024
2021-01-04  277.750000  281.049988  254.737808  31450608  1269.000000
2021-01-05  277.000000  281.750000  255.372314  27393072  1282.000000
2021-01-06  281.399994  285.049988  258.363342  40765708  1300.000000
2021-01-07  287.000000  287.700012  260.765259  30546600  1296.000000

Ticker                                                                    \
Price              High          Low        Close    Adj Close    Volume
Date
2021-01-01  1265.500000  1255.800049  1260.449951  1086.097290   4253550
2021-01-04  1290.000000  1261.150024  1288.250000  1110.051636   7208454
2021-01-05  1299.000000  1275.050049  1293.800049  1114.834106   8145280
2021-01-06  1302.000000  1268.050049  1282.099976  1104.752319   7161715
2021-01-07  1297.650024  1255.500000  1262.150024  1087.562134  10954918

Ticker       LT.NS                                                      \
Price         Open         High          Low        Close    Adj Close
Date
2021-01-01  1283.0  1299.949951  1283.000000  1297.000000  1218.873169
2021-01-04  1305.0  1322.550049  1302.000000  1314.599976  1235.412964
2021-01-05  1307.0  1313.000000  1295.050049  1306.300049  1227.613037
2021-01-06  1308.0  1330.000000  1300.000000  1314.000000  1234.849121
2021-01-07  1330.0  1346.800049  1325.000000  1338.949951  1258.296265

Ticker              HINDUNILVR.NS                                         \
Price        Volume          Open         High          Low        Close
Date
2021-01-01  2058419   2395.399902  2404.000000  2382.000000  2387.550049
2021-01-04  4014636   2405.000000  2430.000000  2400.699951  2426.500000
2021-01-05  2833637   2405.000000  2456.949951  2405.000000  2450.550049
2021-01-06  4615963   2445.800049  2450.000000  2401.600098  2417.300049
2021-01-07  4270598   2432.000000  2432.699951  2365.000000  2368.850098

Ticker                           BHARTIARTL.NS                          \
Price         Adj Close   Volume          Open        High         Low
Date
2021-01-01  2173.496094   830096    502.809753  506.883270  498.834381
2021-01-04  2208.953857  1614486    507.472198  510.907715  502.171722
2021-01-05  2230.847900  2356303    504.527496  507.374054  501.680939
2021-01-06  2200.579102  1641627    505.509064  521.950378  503.644073
2021-01-07  2156.472900  2403881    522.195801  544.232056  517.386047

Ticker                                            ITC.NS              \
Price            Close   Adj Close    Volume        Open        High
Date
2021-01-01  505.656311  488.065765  10377082  202.115906  206.256439
2021-01-04  507.570374  489.913239  13489114  206.063858  207.989685
2021-01-05  504.527496  486.976227  10689423  204.571350  205.341675
2021-01-06  515.619263  497.682129  30837593  203.608429  203.656570
2021-01-07  535.201599  516.583191  39444841  198.456833  199.901199

Ticker                                                   HDFCBANK.NS  \
Price              Low       Close   Adj Close    Volume        Open
Date
2021-01-01  201.538162  205.919418  159.716614  20279389  720.000000
2021-01-04  204.234329  205.486115  159.380524  27927482  719.000000
2021-01-05  202.789948  203.608429  157.924118  18718244  709.599976
2021-01-06  196.916168  197.782791  153.405624  50957586  717.500000
2021-01-07  194.605164  195.279205  151.463791  36298522  716.250000

Ticker
Price             High         Low       Close   Adj Close    Volume
Date
2021-01-01  721.500000  710.299988  712.525024  663.905701   8810938
2021-01-04  719.000000  699.500000  708.000000  659.689453  15740192
2021-01-05  715.375000  704.500000  713.349976  664.674316  14386824
2021-01-06  720.000000  706.549988  710.275024  661.809265  22134050
2021-01-07  716.299988  706.275024  708.125000  659.805908  19894842

In [35]:
data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1402 entries, 2021-01-01 to 2026-08-28
Data columns (total 60 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   (RELIANCE.NS, Open)         1402 non-null   float64
 1   (RELIANCE.NS, High)         1402 non-null   float64
 2   (RELIANCE.NS, Low)          1402 non-null   float64
 3   (RELIANCE.NS, Close)        1402 non-null   float64
 4   (RELIANCE.NS, Adj Close)    1402 non-null   float64
 5   (RELIANCE.NS, Volume)       1402 non-null   int64
 6   (ICICIBANK.NS, Open)        1402 non-null   float64
 7   (ICICIBANK.NS, High)        1402 non-null   float64
 8   (ICICIBANK.NS, Low)         1402 non-null   float64
 9   (ICICIBANK.NS, Close)       1402 non-null   float64
 10  (ICICIBANK.NS, Adj Close)   1402 non-null   float64
 11  (ICICIBANK.NS, Volume)      1402 non-null   int64
 12  (TCS.NS, Open)              1402 non-null   float64
 13  (TCS.NS, High)              1402 non-null   float64
 14  (TCS.NS, Low)               1402 non-null   float64
 15  (TCS.NS, Close)             1402 non-null   float64
 16  (TCS.NS, Adj Close)         1402 non-null   float64
 17  (TCS.NS, Volume)            1402 non-null   int64
 18  (SBIN.NS, Open)             1402 non-null   float64
 19  (SBIN.NS, High)             1402 non-null   float64
 20  (SBIN.NS, Low)              1402 non-null   float64
 21  (SBIN.NS, Close)            1402 non-null   float64
 22  (SBIN.NS, Adj Close)        1402 non-null   float64
 23  (SBIN.NS, Volume)           1402 non-null   int64
 24  (INFY.NS, Open)             1402 non-null   float64
 25  (INFY.NS, High)             1402 non-null   float64
 26  (INFY.NS, Low)              1402 non-null   float64
 27  (INFY.NS, Close)            1402 non-null   float64
 28  (INFY.NS, Adj Close)        1402 non-null   float64
 29  (INFY.NS, Volume)           1402 non-null   int64
 30  (LT.NS, Open)               1402 non-null   float64
 31  (LT.NS, High)               1402 non-null   float64
 32  (LT.NS, Low)                1402 non-null   float64
 33  (LT.NS, Close)              1402 non-null   float64
 34  (LT.NS, Adj Close)          1402 non-null   float64
 35  (LT.NS, Volume)             1402 non-null   int64
 36  (HINDUNILVR.NS, Open)       1402 non-null   float64
 37  (HINDUNILVR.NS, High)       1402 non-null   float64
 38  (HINDUNILVR.NS, Low)        1402 non-null   float64
 39  (HINDUNILVR.NS, Close)      1402 non-null   float64
 40  (HINDUNILVR.NS, Adj Close)  1402 non-null   float64
 41  (HINDUNILVR.NS, Volume)     1402 non-null   int64
 42  (BHARTIARTL.NS, Open)       1402 non-null   float64
 43  (BHARTIARTL.NS, High)       1402 non-null   float64
 44  (BHARTIARTL.NS, Low)        1402 non-null   float64
 45  (BHARTIARTL.NS, Close)      1402 non-null   float64
 46  (BHARTIARTL.NS, Adj Close)  1402 non-null   float64
 47  (BHARTIARTL.NS, Volume)     1402 non-null   int64
 48  (ITC.NS, Open)              1402 non-null   float64
 49  (ITC.NS, High)              1402 non-null   float64
 50  (ITC.NS, Low)               1402 non-null   float64
 51  (ITC.NS, Close)             1402 non-null   float64
 52  (ITC.NS, Adj Close)         1402 non-null   float64
 53  (ITC.NS, Volume)            1402 non-null   int64
 54  (HDFCBANK.NS, Open)         1402 non-null   float64
 55  (HDFCBANK.NS, High)         1402 non-null   float64
 56  (HDFCBANK.NS, Low)          1402 non-null   float64
 57  (HDFCBANK.NS, Close)        1402 non-null   float64
 58  (HDFCBANK.NS, Adj Close)    1402 non-null   float64
 59  (HDFCBANK.NS, Volume)       1402 non-null   int64
dtypes: float64(50), int64(10)
memory usage: 668.1 KB

In [36]:
data.describe()

Ticker  RELIANCE.NS                                                      \
Price          Open         High          Low        Close    Adj Close
count   1402.000000  1402.000000  1402.000000  1402.000000  1402.000000
mean    1247.514119  1258.807383  1235.829337  1246.924142  1232.008526
std      172.309271   173.038933   171.712369   172.360037   175.459442
min      858.112793   879.157166   844.544678   850.059631   831.353882
25%     1128.794006  1140.760712  1117.400726  1126.890259  1109.356293
50%     1234.049988  1244.707520  1222.299988  1234.287537  1219.692017
75%     1392.225037  1407.950012  1381.731262  1393.975006  1384.498596
max     1604.449951  1611.800049  1585.500000  1600.900024  1584.971802

Ticker               ICICIBANK.NS                                         \
Price         Volume         Open         High          Low        Close
count   1.402000e+03  1402.000000  1402.000000  1402.000000  1402.000000
mean    1.407722e+07  1029.552317  1038.742263  1020.576639  1029.886912
std     7.893800e+06   276.148460   277.667574   275.172675   276.406880
min     0.000000e+00   514.599976   529.849976   512.000000   522.349976
25%     9.071406e+06   787.300018   792.625000   778.625000   785.274994
50%     1.213907e+07   974.125000   982.200012   966.200012   973.075012
75%     1.686835e+07  1287.424988  1301.675049  1276.199951  1289.150024
max     9.146198e+07  1500.000000  1500.000000  1478.099976  1488.599976

Ticker                                  TCS.NS                            \
Price     Adj Close        Volume         Open         High          Low
count   1402.000000  1.402000e+03  1402.000000  1402.000000  1402.000000
mean    1006.886896  1.459412e+07  3404.001392  3434.173142  3371.960171
std      281.099123  8.019264e+06   502.578351   506.916654   499.587501
min      500.986786  0.000000e+00  2008.000000  2052.000000  1976.800049
25%      755.363968  9.508749e+06  3152.637512  3175.500000  3125.000000
50%      946.841827  1.276402e+07  3376.625000  3395.400024  3350.324951
75%     1271.041016  1.750887e+07  3740.000000  3763.149963  3702.587463
max     1464.852295  9.612408e+07  4576.000000  4592.250000  4512.000000

Ticker                                              SBIN.NS               \
Price         Close    Adj Close        Volume         Open         High
count   1402.000000  1402.000000  1.402000e+03  1402.000000  1402.000000
mean    3402.059090  3108.550622  2.633789e+06   676.537304   683.158097
std      503.412985   450.895650  1.619321e+06   211.516046   212.875190
min     1982.599976  1971.788818  0.000000e+00   271.899994   280.000000
25%     3149.800049  2837.871155  1.660675e+06   510.400002   516.962509
50%     3376.474976  3065.132202  2.204170e+06   610.000000   614.475006
75%     3733.750000  3334.449219  3.095061e+06   820.224991   825.774994
max     4553.750000  4230.709473  1.633158e+07  1232.000000  1234.699951

Ticker                                                           INFY.NS  \
Price           Low        Close    Adj Close        Volume         Open
count   1402.000000  1402.000000  1402.000000  1.402000e+03  1402.000000
mean     669.207311   676.157311   645.930596  1.836290e+07  1533.891154
std      209.917082   211.425675   219.533485  1.577632e+07   207.326142
min      269.500000   275.649994   249.843369  0.000000e+00  1006.000000
25%      505.025002   511.499992   469.150963  1.036268e+07  1403.174988
50%      604.225006   608.574982   569.287476  1.427243e+07  1519.575012
75%      812.937485   818.750000   794.516281  2.044421e+07  1672.837463
max     1219.699951  1227.800049  1206.060669  2.149557e+08  1995.449951

Ticker                                                                    \
Price          High          Low        Close    Adj Close        Volume
count   1402.000000  1402.000000  1402.000000  1402.000000  1.402000e+03
mean    1548.128102  1518.739267  1533.286449  1409.939778  7.584069e+06
std      209.105304   205.497902   207.593431   194.917464  5.172378e+06
min     1014.000000   982.400024   985.299988   985.299988  0.000000e+00
25%     1415.312500  1386.037506  1403.387543  1270.622986  4.703372e+06
50%     1527.924988  1501.174988  1514.224976  1391.356689  6.329976e+06
75%     1687.787537  1660.737549  1673.812531  1527.384155  8.656160e+06
max     2006.449951  1977.599976  1999.699951  1901.082886  6.908543e+07

Ticker        LT.NS                                                      \
Price          Open         High          Low        Close    Adj Close
count   1402.000000  1402.000000  1402.000000  1402.000000  1402.000000
mean    2796.863374  2823.661976  2768.383957  2795.391940  2726.171314
std      941.367390   947.300957   932.698025   939.987004   955.888916
min     1283.000000  1299.949951  1283.000000  1297.000000  1218.873169
25%     1859.550018  1883.187469  1842.037506  1862.862488  1778.258850
50%     3050.000000  3070.474976  3031.349976  3050.574951  2969.806763
75%     3632.099915  3661.812561  3599.987488  3629.762573  3567.738464
max     4415.500000  4440.000000  4371.700195  4418.100098  4375.364258

Ticker               HINDUNILVR.NS                                         \
Price         Volume          Open         High          Low        Close
count   1.402000e+03   1402.000000  1402.000000  1402.000000  1402.000000
mean    2.298779e+06   2432.668189  2453.867789  2409.015342  2430.833597
std     1.428768e+06    187.063205   188.280706   186.137964   187.160951
min     0.000000e+00   1924.550049  1958.000000  1901.550049  1943.949951
25%     1.442227e+06   2308.025024  2327.200012  2286.724976  2307.600037
50%     1.913202e+06   2425.000000  2444.949951  2402.050049  2424.199951
75%     2.623692e+06   2562.837463  2583.275024  2537.149963  2560.775024
max     1.434966e+07   3020.000000  3035.000000  2969.949951  3028.550049

Ticker                            BHARTIARTL.NS                            \
Price     Adj Close        Volume          Open         High          Low
count   1402.000000  1.402000e+03   1402.000000  1402.000000  1402.000000
mean    2309.016566  1.736946e+06   1191.345772  1203.095606  1179.011243
std      179.132377  1.075876e+06    533.429863   537.689942   529.264040
min     1793.425537  0.000000e+00    502.662506   506.883270   490.343781
25%     2175.143494  1.129405e+06    721.775009   730.750015   711.987488
50%     2315.858887  1.489334e+06    939.799988   948.899994   935.300018
75%     2426.181396  2.021416e+06   1746.125000  1766.425018  1730.799988
max     2909.856689  1.770162e+07   2162.100098  2174.500000  2149.899902

Ticker                                               ITC.NS               \
Price         Close    Adj Close        Volume         Open         High
count   1402.000000  1402.000000  1.402000e+03  1402.000000  1402.000000
mean    1191.024564  1165.064555  8.276460e+06   344.425726   347.317260
std      533.428823   531.228974  1.016353e+07    92.187139    92.715414
min      498.392670   481.054810  0.000000e+00   193.738541   194.364441
25%      720.862488   696.581802  4.227818e+06   258.121460   260.950043
50%      941.125000   916.614319  5.907199e+06   366.678116   369.879822
75%     1749.337463  1713.272522  8.901686e+06   421.756866   424.585434
max     2162.699951  2135.820068  1.985470e+08   501.293671   508.900696

Ticker                                                       HDFCBANK.NS  \
Price           Low        Close    Adj Close        Volume         Open
count   1402.000000  1402.000000  1402.000000  1.402000e+03  1402.000000
mean     341.207143   344.105471   309.734007  1.837011e+07   809.492047
std       91.476178    92.055534    92.701616  1.941289e+07    88.128773
min      191.716431   192.197876   150.492844  0.000000e+00   637.500000
25%      255.497528   259.301048   219.979961  9.745384e+06   745.462509
50%      362.546585   365.642990   320.876907  1.377649e+07   796.825012
75%      418.462227   420.745819   387.664841  2.066307e+07   844.887497
max      500.956665   503.363953   463.949188  4.318516e+08  1018.849976

Ticker
Price          High          Low        Close    Adj Close        Volume
count   1402.000000  1402.000000  1402.000000  1402.000000  1.402000e+03
mean     816.519579   802.828478   809.627248   777.200687  2.629753e+07
std       88.095878    88.141275    88.001927    94.967502  2.402111e+07
min      648.200012   635.799988   640.650024   606.489319  0.000000e+00
25%      753.249985   739.225006   745.675018   706.752701  1.363834e+07
50%      803.837494   790.975006   797.337494   761.171265  2.107560e+07
75%      852.406235   838.756241   845.462479   819.510803  3.286925e+07
max     1020.500000  1008.500000  1012.900024   996.419800  4.453421e+08

In [40]:
data.to_csv("../data/raw/stock_data.csv")

print("Data saved successfully!")

Data saved successfully!