# 📊 Stock Portfolio Optimization & Risk Analysis

## Notebook 02: Data Cleaning & Quality Checks

### Objective
Validate the downloaded stock market data, check for missing values and duplicates, prepare a clean Adjusted Close price dataset, and export it for portfolio analysis.

### Tasks
- Load raw stock data
- Check data quality
- Handle missing values
- Check duplicate rows
- Verify datetime index
- Extract Adjusted Close prices
- Export cleaned dataset

In [ ]:
import pandas as pd 
import numpy as np
import os

print(os.getcwd())

d:\stock optimization project\notebooks

Load Rwa Stock Data

In [ ]:
data = pd.read_csv(
    "../data/raw/stock_data.csv",
    header=[0,1],
    index_col=0,
    parse_dates=True
)

data.head()

Ticker     HINDUNILVR.NS                                                      \
Price               Open         High          Low        Close    Adj Close
Date
2021-01-01   2395.399902  2404.000000  2382.000000  2387.550049  2173.496094
2021-01-04   2405.000000  2430.000000  2400.699951  2426.500000  2208.954102
2021-01-05   2405.000000  2456.949951  2405.000000  2450.550049  2230.848145
2021-01-06   2445.800049  2450.000000  2401.600098  2417.300049  2200.578613
2021-01-07   2432.000000  2432.699951  2365.000000  2368.850098  2156.472900

Ticker                LT.NS                                         ...  \
Price        Volume    Open         High          Low        Close  ...
Date                                                                ...
2021-01-01   830096  1283.0  1299.949951  1283.000000  1297.000000  ...
2021-01-04  1614486  1305.0  1322.550049  1302.000000  1314.599976  ...
2021-01-05  2356303  1307.0  1313.000000  1295.050049  1306.300049  ...
2021-01-06  1641627  1308.0  1330.000000  1300.000000  1314.000000  ...
2021-01-07  2403881  1330.0  1346.800049  1325.000000  1338.949951  ...

Ticker           TCS.NS                                         ITC.NS  \
Price               Low        Close    Adj Close   Volume        Open
Date
2021-01-01  2879.000000  2928.250000  2534.896973  2681440  202.115906
2021-01-04  2940.949951  3039.449951  2631.159668  5113293  206.063858
2021-01-05  3039.600098  3093.000000  2677.516113  5801309  204.571350
2021-01-06  3037.199951  3051.500000  2641.590576  3726716  203.608429
2021-01-07  3000.250000  3032.800049  2625.403564  3717827  198.456833

Ticker
Price             High         Low       Close   Adj Close    Volume
Date
2021-01-01  206.256439  201.538162  205.919418  159.716614  20279389
2021-01-04  207.989685  204.234329  205.486115  159.380524  27927482
2021-01-05  205.341675  202.789948  203.608429  157.924133  18718244
2021-01-06  203.656570  196.916168  197.782791  153.405640  50957586
2021-01-07  199.901199  194.605164  195.279205  151.463791  36298522

[5 rows x 60 columns]

Basic Information

In [ ]:
print("="*50)
print("Dataset Shape")
print(data.shape)

print("="*50)
print("Dataset Information")
data.info()

==================================================
Dataset Shape
(1236, 60)
==================================================
Dataset Information
<class 'pandas.DataFrame'>
DatetimeIndex: 1236 entries, 2021-01-01 to 2025-12-31
Data columns (total 60 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   (HINDUNILVR.NS, Open)       1236 non-null   float64
 1   (HINDUNILVR.NS, High)       1236 non-null   float64
 2   (HINDUNILVR.NS, Low)        1236 non-null   float64
 3   (HINDUNILVR.NS, Close)      1236 non-null   float64
 4   (HINDUNILVR.NS, Adj Close)  1236 non-null   float64
 5   (HINDUNILVR.NS, Volume)     1236 non-null   int64
 6   (LT.NS, Open)               1236 non-null   float64
 7   (LT.NS, High)               1236 non-null   float64
 8   (LT.NS, Low)                1236 non-null   float64
 9   (LT.NS, Close)              1236 non-null   float64
 10  (LT.NS, Adj Close)          1236 non-null   float64
 11  (LT.NS, Volume)             1236 non-null   int64
 12  (INFY.NS, Open)             1236 non-null   float64
 13  (INFY.NS, High)             1236 non-null   float64
 14  (INFY.NS, Low)              1236 non-null   float64
 15  (INFY.NS, Close)            1236 non-null   float64
 16  (INFY.NS, Adj Close)        1236 non-null   float64
 17  (INFY.NS, Volume)           1236 non-null   int64
 18  (HDFCBANK.NS, Open)         1236 non-null   float64
 19  (HDFCBANK.NS, High)         1236 non-null   float64
 20  (HDFCBANK.NS, Low)          1236 non-null   float64
 21  (HDFCBANK.NS, Close)        1236 non-null   float64
 22  (HDFCBANK.NS, Adj Close)    1236 non-null   float64
 23  (HDFCBANK.NS, Volume)       1236 non-null   int64
 24  (SBIN.NS, Open)             1236 non-null   float64
 25  (SBIN.NS, High)             1236 non-null   float64
 26  (SBIN.NS, Low)              1236 non-null   float64
 27  (SBIN.NS, Close)            1236 non-null   float64
 28  (SBIN.NS, Adj Close)        1236 non-null   float64
 29  (SBIN.NS, Volume)           1236 non-null   int64
 30  (RELIANCE.NS, Open)         1236 non-null   float64
 31  (RELIANCE.NS, High)         1236 non-null   float64
 32  (RELIANCE.NS, Low)          1236 non-null   float64
 33  (RELIANCE.NS, Close)        1236 non-null   float64
 34  (RELIANCE.NS, Adj Close)    1236 non-null   float64
 35  (RELIANCE.NS, Volume)       1236 non-null   int64
 36  (BHARTIARTL.NS, Open)       1236 non-null   float64
 37  (BHARTIARTL.NS, High)       1236 non-null   float64
 38  (BHARTIARTL.NS, Low)        1236 non-null   float64
 39  (BHARTIARTL.NS, Close)      1236 non-null   float64
 40  (BHARTIARTL.NS, Adj Close)  1236 non-null   float64
 41  (BHARTIARTL.NS, Volume)     1236 non-null   int64
 42  (ICICIBANK.NS, Open)        1236 non-null   float64
 43  (ICICIBANK.NS, High)        1236 non-null   float64
 44  (ICICIBANK.NS, Low)         1236 non-null   float64
 45  (ICICIBANK.NS, Close)       1236 non-null   float64
 46  (ICICIBANK.NS, Adj Close)   1236 non-null   float64
 47  (ICICIBANK.NS, Volume)      1236 non-null   int64
 48  (TCS.NS, Open)              1236 non-null   float64
 49  (TCS.NS, High)              1236 non-null   float64
 50  (TCS.NS, Low)               1236 non-null   float64
 51  (TCS.NS, Close)             1236 non-null   float64
 52  (TCS.NS, Adj Close)         1236 non-null   float64
 53  (TCS.NS, Volume)            1236 non-null   int64
 54  (ITC.NS, Open)              1236 non-null   float64
 55  (ITC.NS, High)              1236 non-null   float64
 56  (ITC.NS, Low)               1236 non-null   float64
 57  (ITC.NS, Close)             1236 non-null   float64
 58  (ITC.NS, Adj Close)         1236 non-null   float64
 59  (ITC.NS, Volume)            1236 non-null   int64
dtypes: float64(50), int64(10)
memory usage: 589.0 KB

Missing Value

In [ ]:
missing_values = data.isnull().sum()

print(missing_values)

Ticker         Price
HINDUNILVR.NS  Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
LT.NS          Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
INFY.NS        Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
HDFCBANK.NS    Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
SBIN.NS        Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
RELIANCE.NS    Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
BHARTIARTL.NS  Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
ICICIBANK.NS   Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
TCS.NS         Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
ITC.NS         Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
dtype: int64

In [ ]:
print("Total Missing Values:", missing_values.sum())

Total Missing Values: 0

Duplicates Rwa

In [ ]:
duplicates = data.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

Data Types

In [ ]:
print(data.dtypes)

Ticker         Price
HINDUNILVR.NS  Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
LT.NS          Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
INFY.NS        Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
HDFCBANK.NS    Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
SBIN.NS        Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
RELIANCE.NS    Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
BHARTIARTL.NS  Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
ICICIBANK.NS   Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
TCS.NS         Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
ITC.NS         Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
dtype: object

Verify Datetime Index

In [ ]:
print(type(data.index))

print(data.index)

<class 'pandas.DatetimeIndex'>
DatetimeIndex(['2021-01-01', '2021-01-04', '2021-01-05', '2021-01-06',
               '2021-01-07', '2021-01-08', '2021-01-11', '2021-01-12',
               '2021-01-13', '2021-01-14',
               ...
               '2025-12-17', '2025-12-18', '2025-12-19', '2025-12-22',
               '2025-12-23', '2025-12-24', '2025-12-26', '2025-12-29',
               '2025-12-30', '2025-12-31'],
              dtype='datetime64[us]', name='Date', length=1236, freq=None)

Extract Adjusted Close Prices

In [ ]:
adj_close = data.xs("Adj Close", level=1, axis=1)

adj_close.head()

Ticker,HINDUNILVR.NS,LT.NS,INFY.NS,HDFCBANK.NS,SBIN.NS,RELIANCE.NS,BHARTIARTL.NS,ICICIBANK.NS,TCS.NS,ITC.NS
Date,,,,,,,,,,
2021-01-01,2173.496094,1218.873169,1086.097046,663.905701,253.242340,897.047058,494.208191,510.191467,2534.896973,159.716614
2021-01-04,2208.954102,1235.412964,1110.052002,659.689453,254.737793,898.559082,496.078918,514.253601,2631.159668,159.380524
2021-01-05,2230.848145,1227.613037,1114.833984,664.674438,255.372299,887.388245,493.104950,519.621582,2677.516113,157.924133
2021-01-06,2200.578613,1234.849121,1104.752319,661.809265,258.363342,863.986084,503.945587,528.761414,2641.590576,153.405640
2021-01-07,2156.472900,1258.296143,1087.562012,659.805969,260.765259,862.586914,523.084534,523.345154,2625.403564,151.463791

Rename Columns

In [ ]:
adj_close.columns = [
    col.replace(".NS", "")
    for col in adj_close.columns
]

adj_close.head()

,HINDUNILVR,LT,INFY,HDFCBANK,SBIN,RELIANCE,BHARTIARTL,ICICIBANK,TCS,ITC
Date,,,,,,,,,,
2021-01-01,2173.496094,1218.873169,1086.097046,663.905701,253.242340,897.047058,494.208191,510.191467,2534.896973,159.716614
2021-01-04,2208.954102,1235.412964,1110.052002,659.689453,254.737793,898.559082,496.078918,514.253601,2631.159668,159.380524
2021-01-05,2230.848145,1227.613037,1114.833984,664.674438,255.372299,887.388245,493.104950,519.621582,2677.516113,157.924133
2021-01-06,2200.578613,1234.849121,1104.752319,661.809265,258.363342,863.986084,503.945587,528.761414,2641.590576,153.405640
2021-01-07,2156.472900,1258.296143,1087.562012,659.805969,260.765259,862.586914,523.084534,523.345154,2625.403564,151.463791

In [ ]:
adj_close.info()

adj_close.describe()

<class 'pandas.DataFrame'>
DatetimeIndex: 1236 entries, 2021-01-01 to 2025-12-31
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   HINDUNILVR  1236 non-null   float64
 1   LT          1236 non-null   float64
 2   INFY        1236 non-null   float64
 3   HDFCBANK    1236 non-null   float64
 4   SBIN        1236 non-null   float64
 5   RELIANCE    1236 non-null   float64
 6   BHARTIARTL  1236 non-null   float64
 7   ICICIBANK   1236 non-null   float64
 8   TCS         1236 non-null   float64
 9   ITC         1236 non-null   float64
dtypes: float64(10)
memory usage: 106.2 KB

,HINDUNILVR,LT,INFY,HDFCBANK,SBIN,RELIANCE,BHARTIARTL,ICICIBANK,TCS,ITC
count,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000
mean,2324.134159,2561.489259,1432.471855,773.386162,592.628865,1214.878506,1081.593412,970.100703,3212.910944,311.684277
std,181.031214,895.664184,186.306541,97.024789,173.773399,178.600536,495.927975,270.403227,393.856993,98.423951
min,1793.425293,1218.873169,1067.657471,606.489258,249.843353,831.353760,487.108978,505.210449,2510.275146,150.492859
25%,2192.340942,1713.082184,1308.523773,700.672333,453.792831,1095.659424,692.349548,730.230698,2918.793518,205.435749
50%,2336.585327,2352.572632,1417.212952,756.372040,551.850891,1189.996460,844.741180,917.816010,3117.785156,364.465210
75%,2439.125122,3487.027161,1533.279907,815.605011,767.465729,1376.709686,1565.091003,1225.779266,3415.839661,390.751511
max,2909.856934,4052.715820,1901.083008,996.419800,966.479187,1581.824463,2162.699951,1477.201782,4253.906250,463.949249

In [ ]:
import os

os.makedirs("data/processed", exist_ok=True)

import os

os.makedirs("../data/processed", exist_ok=True)

adj_close.to_csv("../data/processed/adjusted_close.csv")