# 📊 Stock Portfolio Optimization & Risk Analysis

## Notebook 02: Data Cleaning & Quality Checks

### Objective
Validate the downloaded stock market data, check for missing values and duplicates, prepare a clean Adjusted Close price dataset, and export it for portfolio analysis.

### Tasks
- Load raw stock data
- Check data quality
- Handle missing values
- Check duplicate rows
- Verify datetime index
- Extract Adjusted Close prices
- Export cleaned dataset

In [1]:
import pandas as pd 
import numpy as np

Load Rwa Stock Data

In [2]:
data = pd.read_csv(
    "../data/raw/stock_data.csv",
    header=[0,1],
    index_col=0,
    parse_dates=True
)

data.head()

Ticker       LT.NS                                                      \
Price         Open         High          Low        Close    Adj Close
Date
2021-01-01  1283.0  1299.949951  1283.000000  1297.000000  1218.873169
2021-01-04  1305.0  1322.550049  1302.000000  1314.599976  1235.412964
2021-01-05  1307.0  1313.000000  1295.050049  1306.300049  1227.613037
2021-01-06  1308.0  1330.000000  1300.000000  1314.000000  1234.848999
2021-01-07  1330.0  1346.800049  1325.000000  1338.949951  1258.296143

Ticker              BHARTIARTL.NS                                      ...  \
Price        Volume          Open        High         Low       Close  ...
Date                                                                   ...
2021-01-01  2058419    502.809753  506.883270  498.834381  505.656311  ...
2021-01-04  4014636    507.472198  510.907715  502.171722  507.570374  ...
2021-01-05  2833637    504.527496  507.374054  501.680939  504.527496  ...
2021-01-06  4615963    505.509064  521.950378  503.644073  515.619263  ...
2021-01-07  4270598    522.195801  544.232056  517.386047  535.201599  ...

Ticker          INFY.NS                                           TCS.NS  \
Price               Low        Close    Adj Close    Volume         Open
Date
2021-01-01  1255.800049  1260.449951  1086.097412   4253550  2880.000000
2021-01-04  1261.150024  1288.250000  1110.051880   7208454  2950.000000
2021-01-05  1275.050049  1293.800049  1114.834106   8145280  3039.600098
2021-01-06  1268.050049  1282.099976  1104.752441   7161715  3100.000000
2021-01-07  1255.500000  1262.150024  1087.562134  10954918  3075.000000

Ticker
Price              High          Low        Close    Adj Close   Volume
Date
2021-01-01  2940.000000  2879.000000  2928.250000  2534.897217  2681440
2021-01-04  3050.750000  2940.949951  3039.449951  2631.159424  5113293
2021-01-05  3114.250000  3039.600098  3093.000000  2677.515869  5801309
2021-01-06  3113.500000  3037.199951  3051.500000  2641.590576  3726716
2021-01-07  3080.850098  3000.250000  3032.800049  2625.403076  3717827

[5 rows x 60 columns]

Basic Information

In [3]:
print("="*50)
print("Dataset Shape")
print(data.shape)

print("="*50)
print("Dataset Information")
data.info()

==================================================
Dataset Shape
(1236, 60)
==================================================
Dataset Information
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1236 entries, 2021-01-01 to 2025-12-31
Data columns (total 60 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   (LT.NS, Open)               1236 non-null   float64
 1   (LT.NS, High)               1236 non-null   float64
 2   (LT.NS, Low)                1236 non-null   float64
 3   (LT.NS, Close)              1236 non-null   float64
 4   (LT.NS, Adj Close)          1236 non-null   float64
 5   (LT.NS, Volume)             1236 non-null   int64
 6   (BHARTIARTL.NS, Open)       1236 non-null   float64
 7   (BHARTIARTL.NS, High)       1236 non-null   float64
 8   (BHARTIARTL.NS, Low)        1236 non-null   float64
 9   (BHARTIARTL.NS, Close)      1236 non-null   float64
 10  (BHARTIARTL.NS, Adj Close)  1236 non-null   float64
 11  (BHARTIARTL.NS, Volume)     1236 non-null   int64
 12  (RELIANCE.NS, Open)         1236 non-null   float64
 13  (RELIANCE.NS, High)         1236 non-null   float64
 14  (RELIANCE.NS, Low)          1236 non-null   float64
 15  (RELIANCE.NS, Close)        1236 non-null   float64
 16  (RELIANCE.NS, Adj Close)    1236 non-null   float64
 17  (RELIANCE.NS, Volume)       1236 non-null   int64
 18  (SBIN.NS, Open)             1236 non-null   float64
 19  (SBIN.NS, High)             1236 non-null   float64
 20  (SBIN.NS, Low)              1236 non-null   float64
 21  (SBIN.NS, Close)            1236 non-null   float64
 22  (SBIN.NS, Adj Close)        1236 non-null   float64
 23  (SBIN.NS, Volume)           1236 non-null   int64
 24  (HINDUNILVR.NS, Open)       1236 non-null   float64
 25  (HINDUNILVR.NS, High)       1236 non-null   float64
 26  (HINDUNILVR.NS, Low)        1236 non-null   float64
 27  (HINDUNILVR.NS, Close)      1236 non-null   float64
 28  (HINDUNILVR.NS, Adj Close)  1236 non-null   float64
 29  (HINDUNILVR.NS, Volume)     1236 non-null   int64
 30  (HDFCBANK.NS, Open)         1236 non-null   float64
 31  (HDFCBANK.NS, High)         1236 non-null   float64
 32  (HDFCBANK.NS, Low)          1236 non-null   float64
 33  (HDFCBANK.NS, Close)        1236 non-null   float64
 34  (HDFCBANK.NS, Adj Close)    1236 non-null   float64
 35  (HDFCBANK.NS, Volume)       1236 non-null   int64
 36  (ICICIBANK.NS, Open)        1236 non-null   float64
 37  (ICICIBANK.NS, High)        1236 non-null   float64
 38  (ICICIBANK.NS, Low)         1236 non-null   float64
 39  (ICICIBANK.NS, Close)       1236 non-null   float64
 40  (ICICIBANK.NS, Adj Close)   1236 non-null   float64
 41  (ICICIBANK.NS, Volume)      1236 non-null   int64
 42  (ITC.NS, Open)              1236 non-null   float64
 43  (ITC.NS, High)              1236 non-null   float64
 44  (ITC.NS, Low)               1236 non-null   float64
 45  (ITC.NS, Close)             1236 non-null   float64
 46  (ITC.NS, Adj Close)         1236 non-null   float64
 47  (ITC.NS, Volume)            1236 non-null   int64
 48  (INFY.NS, Open)             1236 non-null   float64
 49  (INFY.NS, High)             1236 non-null   float64
 50  (INFY.NS, Low)              1236 non-null   float64
 51  (INFY.NS, Close)            1236 non-null   float64
 52  (INFY.NS, Adj Close)        1236 non-null   float64
 53  (INFY.NS, Volume)           1236 non-null   int64
 54  (TCS.NS, Open)              1236 non-null   float64
 55  (TCS.NS, High)              1236 non-null   float64
 56  (TCS.NS, Low)               1236 non-null   float64
 57  (TCS.NS, Close)             1236 non-null   float64
 58  (TCS.NS, Adj Close)         1236 non-null   float64
 59  (TCS.NS, Volume)            1236 non-null   int64
dtypes: float64(50), int64(10)
memory usage: 589.0 KB

Missing Value

In [4]:
missing_values = data.isnull().sum()

print(missing_values)

Ticker         Price
LT.NS          Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
BHARTIARTL.NS  Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
RELIANCE.NS    Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
SBIN.NS        Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
HINDUNILVR.NS  Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
HDFCBANK.NS    Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
ICICIBANK.NS   Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
ITC.NS         Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
INFY.NS        Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
TCS.NS         Open         0
               High         0
               Low          0
               Close        0
               Adj Close    0
               Volume       0
dtype: int64

In [6]:
print("Total Missing Values:", missing_values.sum())

Total Missing Values: 0

Duplicates Rwa

In [7]:
duplicates = data.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

Data Types

In [8]:
print(data.dtypes)

Ticker         Price
LT.NS          Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
BHARTIARTL.NS  Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
RELIANCE.NS    Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
SBIN.NS        Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
HINDUNILVR.NS  Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
HDFCBANK.NS    Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
ICICIBANK.NS   Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
ITC.NS         Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
INFY.NS        Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
TCS.NS         Open         float64
               High         float64
               Low          float64
               Close        float64
               Adj Close    float64
               Volume         int64
dtype: object

Verify Datetime Index

In [9]:
print(type(data.index))

print(data.index)

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
DatetimeIndex(['2021-01-01', '2021-01-04', '2021-01-05', '2021-01-06',
               '2021-01-07', '2021-01-08', '2021-01-11', '2021-01-12',
               '2021-01-13', '2021-01-14',
               ...
               '2025-12-17', '2025-12-18', '2025-12-19', '2025-12-22',
               '2025-12-23', '2025-12-24', '2025-12-26', '2025-12-29',
               '2025-12-30', '2025-12-31'],
              dtype='datetime64[ns]', name='Date', length=1236, freq=None)

Extract Adjusted Close Prices

In [10]:
adj_close = data.xs("Adj Close", level=1, axis=1)

adj_close.head()

Ticker,LT.NS,BHARTIARTL.NS,RELIANCE.NS,SBIN.NS,HINDUNILVR.NS,HDFCBANK.NS,ICICIBANK.NS,ITC.NS,INFY.NS,TCS.NS
Date,,,,,,,,,,
2021-01-01,1218.873169,494.208160,897.047119,253.242310,2173.496338,663.905640,510.191437,159.716629,1086.097412,2534.897217
2021-01-04,1235.412964,496.078949,898.559082,254.737808,2208.954102,659.689453,514.253662,159.380524,1110.051880,2631.159424
2021-01-05,1227.613037,493.104950,887.388245,255.372314,2230.847900,664.674377,519.621521,157.924164,1114.834106,2677.515869
2021-01-06,1234.848999,503.945557,863.986084,258.363342,2200.579102,661.809204,528.761475,153.405624,1104.752441,2641.590576
2021-01-07,1258.296143,523.084534,862.586975,260.765259,2156.472900,659.805908,523.345154,151.463776,1087.562134,2625.403076

Rename Columns

In [11]:
adj_close.columns = [
    col.replace(".NS", "")
    for col in adj_close.columns
]

adj_close.head()

,LT,BHARTIARTL,RELIANCE,SBIN,HINDUNILVR,HDFCBANK,ICICIBANK,ITC,INFY,TCS
Date,,,,,,,,,,
2021-01-01,1218.873169,494.208160,897.047119,253.242310,2173.496338,663.905640,510.191437,159.716629,1086.097412,2534.897217
2021-01-04,1235.412964,496.078949,898.559082,254.737808,2208.954102,659.689453,514.253662,159.380524,1110.051880,2631.159424
2021-01-05,1227.613037,493.104950,887.388245,255.372314,2230.847900,664.674377,519.621521,157.924164,1114.834106,2677.515869
2021-01-06,1234.848999,503.945557,863.986084,258.363342,2200.579102,661.809204,528.761475,153.405624,1104.752441,2641.590576
2021-01-07,1258.296143,523.084534,862.586975,260.765259,2156.472900,659.805908,523.345154,151.463776,1087.562134,2625.403076

In [12]:
adj_close.info()

adj_close.describe()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1236 entries, 2021-01-01 to 2025-12-31
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LT          1236 non-null   float64
 1   BHARTIARTL  1236 non-null   float64
 2   RELIANCE    1236 non-null   float64
 3   SBIN        1236 non-null   float64
 4   HINDUNILVR  1236 non-null   float64
 5   HDFCBANK    1236 non-null   float64
 6   ICICIBANK   1236 non-null   float64
 7   ITC         1236 non-null   float64
 8   INFY        1236 non-null   float64
 9   TCS         1236 non-null   float64
dtypes: float64(10)
memory usage: 106.2 KB

,LT,BHARTIARTL,RELIANCE,SBIN,HINDUNILVR,HDFCBANK,ICICIBANK,ITC,INFY,TCS
count,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000
mean,2561.489260,1081.593413,1214.878505,592.628865,2324.134170,773.386162,970.100704,311.684277,1432.471854,3212.910943
std,895.664190,495.927974,178.600537,173.773399,181.031225,97.024788,270.403226,98.423951,186.306535,393.857009
min,1218.873169,487.109009,831.353760,249.843369,1793.425293,606.489258,505.210388,150.492859,1067.657471,2510.275635
25%,1713.082214,692.349503,1095.659424,453.792809,2192.340515,700.672333,730.230682,205.435749,1308.523804,2918.793518
50%,2352.572510,844.741180,1189.996460,551.850922,2336.585327,756.372009,917.816040,364.465195,1417.213013,3117.785278
75%,3487.027161,1565.091003,1376.709686,767.465729,2439.125122,815.605011,1225.779266,390.751564,1533.279907,3415.839539
max,4052.715820,2162.699951,1581.824463,966.479187,2909.856689,996.419800,1477.201782,463.949249,1901.083008,4253.906738

In [13]:
adj_close.to_csv("../data/processed/adjusted_close.csv")

print("Clean dataset exported successfully!")

OSError: Cannot save file into a non-existent directory: '..\data\processed'